/*
 * This source file was generated by the Gradle 'init' task
 */
package pa10;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class GraphTest {
    @Test void appHasAGreeting() {
        Graph g = new Graph();
        g.addEdge(1, 2);
        g.addEdge(2, 3);
        assertEquals("1 2 3", g.topologicalSort());
        assertEquals("1 2 3", g.topologicalSort());
    }
}
