/*
 * This source file was generated by the Gradle 'init' task
 */

package pa10;
/** 
 * Graph interface for a directed graph with vertices numbered from 0 to n-1.
 */
interface Graph {

    /**
     *  Add an edge between two vertices.
     *  @param v vertex 1 (0-indexed)
     *  @param w vertex 2 (0-indexed)
     * 
     */
    public void addEdge(int v, int w);

    /**
     * Topological sort of the graph, using DFS.
     * 
     * @return an array of vertices in topological order
     * 
     */
    public String topologicalSort();

    /**
     * Topological sort of the graph, using Kahn's algorithm.
     * 
     * @return an array of vertices in topological order
     * 
     */
    public String kahn();

}
